Feature/account registration
BartoliniAndBorderCollies/Library_Manager_Official pull request #4
Opened 2023-06-01 10:07 UTC by BartoliniAndBorderCollies

#### Issue: https://trello.com/c/pOFlgCXI

### Description
User of the application is now able to write a command and create account in the database.

### Motivation
This is the basic functionality of the application.

### Changes introduced by this PR

- Corrections of commits from the previous PR
- improvement of structure of the application

Furthermore, this branch makes the whole functionality to create an account for the user by:

- creating a run() in `Main`
- creating `MenuController` which interacts with the user to listen the command
- reacting for user input by sending the request through command class, controller class, service class to the repository class
- taking the necessary information from the user in order to create an account in the db

### Testing
Application connects and persist data in DB.

2023-06-01 12:21 UTC, JasinskiSz requested changes
I left some comments requesting changes. The first biggest issue is with do while loop in main where inside is a run method. It doesn't make sense as you'll even print multiple "Welcome to the Library Manager app!" messages which are meant to be showed once on the app start for user.

Take a look at the places where I asked for changes and reply to them if something is unclear to you. Thanks!

2023-06-01 12:21 UTC, JasinskiSz commented on src/main/java/org/klodnicki/Main.java
> +            MenuController menuController = new MenuController();
Do not create new object of MenuController inside of a loop.

2023-06-01 12:21 UTC, JasinskiSz commented on src/main/java/org/klodnicki/Main.java
> +            menuController.run();
run() shouldn't be in loop. It's meant to be run only once.

2023-06-01 12:21 UTC, JasinskiSz commented on src/main/java/org/klodnicki/controller/AccountController.java
> +            accountService.create(firstName, secondName, lastName, pesel, phoneNumber, email, address);
Try block is unnecessarily so large. It should only contain create method which throws your `IllegalArgumentException`.

2023-06-01 12:21 UTC, JasinskiSz commented on src/main/java/org/klodnicki/controller/AccountController.java
> +    }
The method ends without ever giving user information about successfully creating account.

2023-06-01 12:21 UTC, JasinskiSz commented on src/main/java/org/klodnicki/controller/MenuController.java
> +        menuView.update("");
Why is there view updated with empty String?

2023-06-01 12:21 UTC, JasinskiSz commented on src/main/java/org/klodnicki/entity/Account.java
> +    @Column(nullable = false)
Add property `name` to the `@Column` to follow database convention of naming columns.
i.e. `@Column(name = "first_name")`

2023-06-01 12:21 UTC, JasinskiSz commented on src/main/java/org/klodnicki/service/MenuService.java
> +        // TODO: walidacja userInput
Is this TODO still to be done?

2023-06-01 12:21 UTC, JasinskiSz commented on src/main/java/org/klodnicki/model/Menu.java
> +    public List<MenuCommand> getCommands() {
is this method used?

2023-06-01 12:22 UTC, JasinskiSz commented
Also I forgot. I didn't checked it in my IntelliJ. I'll do that in the evening, after 7 PM.

2023-06-01 13:58 UTC, BartoliniAndBorderCollies commented
OK thanks for your comments. changes done. Please check.

2023-06-01 18:23 UTC, JasinskiSz commented on src/main/java/org/klodnicki/model/Menu.java
> +    public List<MenuCommand> getCommands() {
It is now used in `MenuService`. Great job!

2023-06-01 18:35 UTC, JasinskiSz requested changes
Great job with `Account` class and overall!

One more thing with logical error in the `MenuController` class. Please check my review comment there.

2023-06-01 18:35 UTC, JasinskiSz commented on src/main/java/org/klodnicki/controller/MenuController.java
> +        String userInput = askForInput(USER_COMMAND);
Lines 28-31:
This is incorrect. What you want to achieve here is print either `OPERATION_SUCCESS` or `ABORT_OPERATION`.
Ask yourself now @BartoliniAndBorderCollies, what will happen if `executeCommand` return true? And what will happen when the same command returns false?

SPOILER and answer below:
If that method return `false`, app will correctly print only `ABORT_OPERATION`, but when it returns `true` it'll print both the success and abort messages.

2023-06-01 18:35 UTC, JasinskiSz commented on src/main/java/org/klodnicki/controller/AccountController.java
> +    }
Those messages are now created in `MenuController`.

2023-06-01 18:36 UTC, JasinskiSz commented on src/main/java/org/klodnicki/service/MenuService.java
> +        // TODO: walidacja userInput
Done, TODO no longer in the code.

2023-06-01 18:36 UTC, JasinskiSz commented on src/main/java/org/klodnicki/entity/Account.java
> +    @Column(nullable = false)
@BartoliniAndBorderCollies great job on this issue! Done.

2023-06-01 18:36 UTC, JasinskiSz commented on src/main/java/org/klodnicki/controller/MenuController.java
> +        menuView.update("");
Done.

2023-06-02 08:24 UTC, BartoliniAndBorderCollies commented
OK great! thank you so much for that suggestion! I made changes, everything should be fine right now!

2023-06-04 20:33 UTC, JasinskiSz approved these changes, later dismissed
I'm only leaving a suggestion to change name of one constant.
Other than that, you can go with merge.

2023-06-04 20:33 UTC, JasinskiSz commented on src/main/java/org/klodnicki/controller/AccountController.java
> +    private static final String SUCCESS = "Success! An account has been created!";
```suggestion
    private static final String SUCCESS_ACCOUNT_CREATION = "Success! An account has been created!";
```

2023-06-04 20:33 UTC, JasinskiSz commented on src/main/java/org/klodnicki/controller/AccountController.java
> +        menuController.displayOnMenu(SUCCESS);
```suggestion
        menuController.displayOnMenu(SUCCESS_ACCOUNT_CREATION);
```

2023-06-05 07:26 UTC, BartoliniAndBorderCollies commented on src/main/java/org/klodnicki/controller/AccountController.java
> +        menuController.displayOnMenu(SUCCESS);
OK! done!

2023-06-05 09:17 UTC, JasinskiSz approved these changes
Looking good

2023-06-05 09:17 UTC, merged